### ISSUE TITLE
[JumpToTop] discord crash when opening any image

### ISSUE THREAD

**Issue by Lucas1423o** [Huderon/BetterDiscordPlugins#2]
[JumpToTop]

when having the plugin enabled, opening any image results in a kind of.. soft crash? it doesn't close, instead it shows:

"
well, this is awkward
looks like discord has crashed unexpectedly....
we've tracked the error and will get right on it.
"

**Comment by Huderon** [comment]
Which version of the plugin are you using? I'm not sure about opening an image, but v1.0.1 will crash any time the channel header is rendered. I've pushed a fix, which you can download from the repo, but it might be a while before the updated is accepted by BD staff

**Comment by IronLucario2012** [comment]
Had the same issue with this plugin crashing discord on load, nice to know there's a fix already waiting to be pushed through.

**Comment by PlepperGuy** [comment]
This plugin is causing crashes for me as well. All plugins are up to date. Removing this plugin stops crashes. Please let me know if you need any help troubleshooting.

**Comment by PlepperGuy** [comment]
> Which version of the plugin are you using? I'm not sure about opening an image, but v1.0.1 will crash any time the channel header is rendered. I've pushed a fix, which you can download from the repo, but it might be a while before the updated is accepted by BD staff

just saw this.

**Comment by Lucatir** [comment]
Edit: As opposed to what I initially wrote, the git version (1.0.2) actually does solve the problem (turns out I had another plugin that was also causing crashes after I had updated Discord). Thank you, Huderon.

**Comment by Huderon** [comment]
The update was approved a few hours ago. If anyone is still having this issue, you should now be able to update through the app or download the updated version from the BDsite
