### ISSUE TITLE
Crashing when loading any channel.

### ISSUE THREAD

**Issue by HimitsuYami** [Huderon/BetterDiscordPlugins#3]
This plugin is crashing me whenever I try to load into any channel. According to the Crash Recovery plugin I'm using, I should tell you this:
[discord.com-1713559786216.log](https://github.com/Huderon/BetterDiscordPlugins/files/15045527/discord.com-1713559786216.log)

I have no idea what any of this means, but I do know that disabling this plugin stopped my crashing, turning it back on caused me to crash again.

**Comment by Huderon** [comment]
Duplicate of #2
