### ISSUE TITLE
MentionFilter - Option to manual mention

### ISSUE THREAD

**Issue by elofajnekonto** [Huderon/BetterDiscordPlugins#4]
Plugin forces to mention all reply messages or when the plugin settings are set differently you can't manually check to mention when replying.

I think the plugin should work like SuppressReplyMentions by Strencher where even with the plugin you could still mention when replying without turning off the plugin

**Comment by Huderon** [comment]
Just pushed an update that should fix this. Let me know if there's any issues.

 It probably won't be processed by BD staff for a bit, but you can grab it from here directly if you're eager

**Comment by elofajnekonto** [comment]
Awesome
Thanks a lot
